---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-yaml
      - id: trailing-whitespace
      - id: detect-private-key
  - repo: https://github.com/psf/black
    rev: 22.12.0
    hooks:
      - id: black
  - repo: https://github.com/pycqa/isort
    rev: 5.11.5
    hooks:
      - id: isort
        name: isort (python)
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    # Ruff version.
    rev: "v0.0.261"
    hooks:
      - id: ruff
  - repo: https://github.com/dbt-checkpoint/dbt-checkpoint
    files: ^/pydata_bcn_dbt/
    # https://docs.getdbt.com/blog/enforcing-rules-pre-commit-dbt
    rev: v1.0.0
    hooks:
      - id: dbt-docs-generate
        # https://github.com/dbt-checkpoint/dbt-checkpoint/pull/48#issuecomment-1011467026
        args: ["--cmd-flags", "++project-dir", "pydata_bcn_dbt/", "++profiles-dir", "."]
      - id: check-model-has-properties-file
        name: Check that all models are listed in a YAML file
        files: ^/models/
        args: ["--cmd-flags", "++project-dir", "pydata_bcn_dbt/", "++profiles-dir", "."]
      - id: check-model-has-tests
        name: Check that all models have tests
        files: ^/models/
        args: ["--cmd-flags", "++project-dir", "pydata_bcn_dbt/", "++profiles-dir", "."]
fail_fast: true
files: ".*"
exclude: "desktop.ini" # Windows
default_language_version:
  python: python3.10.9
