---
version: "3.7"

services:
  app:
    image: pydata-bcn-dbt-fal:latest
    build:
      context: .
      dockerfile: Dockerfile
      target: app
    networks:
      db_nw:
        aliases:
          - app-dev
  app-dev:
    image: pydata-bcn-dbt-fal:app-dev-latest
    build:
      context: .
      dockerfile: Dockerfile
      target: develop
    command: /bin/sh -c "while sleep 1000; do :; done"
    user: pydata
    volumes:
      - .:/app:cached
    networks:
      db_nw:
        aliases:
          - app-dev

  db-dev:
    image: postgres:14
    restart: always
    environment:
      - POSTGRES_USER=pydata_dev
      - POSTGRES_PASSWORD=bcn_dev
      - POSTGRES_DB=bcn_dev
    volumes:
      - pgdata_dev:/var/lib/postgresql/data
    ports:
      - 5559:5432
    networks:
      db_nw:
        aliases:
          - postgres_dev

  db-prod:
    image: postgres:14
    restart: always
    environment:
      - POSTGRES_USER=pydata_prod
      - POSTGRES_PASSWORD=bcn_prod
      - POSTGRES_DB=bcn_prod
    volumes:
      - pgdata_prod:/var/lib/postgresql/data
    ports:
      - 5555:5432
    networks:
      db_nw:
        aliases:
          - postgres_prod

  pgadmin:
    image: dpage/pgadmin4:7.0
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=pydata@yopmail.com
      - PGADMIN_DEFAULT_PASSWORD=bcn
    volumes:
      - ./servers.json:/pgadmin4/servers.json
    ports:
      - 5050:80
    depends_on:
      - db-dev
      - db-prod
    networks:
      db_nw:
        aliases:
          - pgadmin

networks:
  db_nw:
    driver: bridge

volumes:
  pgdata_dev:
  pgdata_prod:
