---
version: "3.9"

services:
  dev_env:
    container_name: dev_env
    image: ghcr.io/som-energia/pydata-bcn-dbt-fal:latest
    command: /bin/sh -c "while sleep 1000; do :; done"
    build:
      context: .
      dockerfile: Dockerfile
      target: dev_env
      cache_from:
        - ghcr.io/som-energia/pydata-bcn-dbt-fal:latest
    volumes:
      - .:/app:cached
      - python_venv:/app/.venv
    environment:
      - NOVU_API_KEY=${NOVU_API_KEY}
      - NOVU_SUBSCRIBER_ID=${NOVU_SUBSCRIBER_ID}
      - NOVU_APP_NAME=${NOVU_APP_NAME}
    networks:
      db_nw:
        aliases:
          - app
      novu_nw:
        aliases:
          - app

networks:
  db_nw:
    driver: bridge
    name: db_nw
  novu_nw:
    driver: bridge
    name: novu_nw

volumes:
  pgdata_dev:
  pgdata_prod:
  python_venv:
